### ISSUE TITLE
Folia support

### ISSUE THREAD

**Issue by Trard** [KoxSosen/SimpleVoiceBans#6]
SimpleVoiceChat supports Folia
LibertyBans supports Folia

So, it would be natural if this plugin also supports Folia

**Comment by KoxSosen** [comment]
Thank you for the suggestion! This will be added in the next release.

**Comment by KoxSosen** [comment]
Folia support is available on the master branch as of 8075ea4. If you know how to compile plugins using gradle, feel free to experiment with it.
